travel_social/social/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'social'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('create-post/', views.create_post, name='create_post'),
    path('<int:pk>/edit/', views.edit_post, name='edit_post'),
    path('<int:pk>/like/', views.like_post, name='like_post'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

travel_social/travel_social/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('social/', include('social.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

travel_social/social/models.py
from django.conf import settings
from django.db import models

from django.contrib.auth import get_user_model
from django.utils import timezone
User=get_user_model()



# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(default=timezone.now)
    published = models.DateTimeField(blank=True, null=True)
    title = models.CharField(max_length=250)
    destination = models.CharField(max_length=50)
    dest_type = models.CharField(max_length=50)
    location = models.CharField(max_length=250)
    image = models.ImageField(upload_to='uploads/', height_field=None, width_field=None)
    content = models.TextField()
    likes = models.ManyToManyField(User, blank=True, related_name="collected_likes")

    def total_likes(self):
        return self.likes.count()

    def publish(self):
        self.published = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def created_recently(self):
        return self.created >= timezone.now() - datetime.timedelta(days=1)

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models .ForeignKey(Post, related_name="Comments", on_delete=models.CASCADE)
    text = models.TextField()
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return '%s - %s' % (self.post.title, self.post.user)

travel_social/social/forms.py
from django.forms import ModelForm
from django.db.models import fields
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    title = forms.TextInput()
    destination = forms.TextInput()
    dest_type = forms.TextInput()
    location = forms.TextInput()
    image = forms.ImageField()
    content = forms.Textarea()
    class Meta:
        model = Post
        fields = (
            'title',
            'destination',
            'dest_type',
            'location',
            'image',
            'content',
        )
        

class CommentForm(forms.ModelForm):
    text = forms.Textarea()
    class Meta:
        model = Comment
        fields = (
            'text',
        ) 
        widgets = {'text': forms.Textarea(attrs={'placeholder': 'comment', 'help_text': ''})}
        labels = {'text' : ''}

    

travel_social/social/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse
from django.template import loader
from django.contrib.auth.models import User
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.utils import timezone
from django.contrib.auth.decorators import login_required

# Create your views here.   
def index(request):
    template = 'social/index.html'
    all_posts = Post.objects.all

    context = {
        'all_posts': all_posts,
    }
    return render(request, template, context)

def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm()

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.user = request.user
            comment.created = timezone.now()
            comment.text = request.POST['text']
            comment.save()
            return redirect('social:detail', post.id)
    else:
        form: CommentForm()

    context = {
        'post': post,
        'form': form,
    }
    return render(request, 'social/detail.html', context)

@login_required
def create_post(request):
    template = 'social/post.html'
    form = PostForm(request.POST, request.FILES)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        print(request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.created = timezone.now()
            post.title = request.POST['title']
            post.dest_type = request.POST['dest_type']
            post.location = request.POST['location']
            post.image = request.FILES['image']
            post.content = request.POST['content']
            post.save()
            return redirect('social:detail', post.id)
    else:
        form: PostForm()

    context = {
        'form': PostForm,
    }
    return render(request, template, context)

def edit_post(request, pk):
    template = 'social/edit.html'
    post = get_object_or_404(Post, pk=pk)   
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(Commit=False)
            post.user = request.user
            post.created = timezone.now()
            post.save()
            return redirect('social:detail', pk=post.pk)
        else:
            form = PostForm(instance=post)
    
    context = {
        'form': PostForm
    }
    return render(request, template, context)

def like_post(request, pk):
    if request.method == 'POST':
        instance = Post.objects.get(pk=pk)
        if not instance.likes.filter(id=request.user.id).exists():
            instance.likes.add(request.user)
            instance.save()
            return render(request, 'social/likes.html', context={'post': instance})
        else:
            instance.likes.remove(request.user)
            instance.save()
            return render(request, 'social/likes.html', context={'post': instance})

travel_social/social/templates/social/comment.html
<div class="comment-section">
    <h3>Comments <small>( {{post.Comments.count}} )</small></h3>
    
    <form action="{% url 'social:detail' post.id %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" value="Submit">comment</button>
    </form>

    <div class="comment-text">
        {% if not post.Comments.all %}
        <p>This post has no comments yet... be the first to comment.</p>
        {% else %}
            {% for comment in post.Comments.all %}
                <p><strong>{{ comment.user.username }}</strong> <small>{{ comment.created }}</small></p>
                
                <blockquote>{{ comment.text }}</blockquote>
            {% endfor %}
        {% endif %}
    </div>
    
</div>

travel_social/social/templates/social/detail.html
{% extends 'base.html' %}
{% load static %}
{% load cache_bust %}

{% block title %}{{ post.title }} - @{{  post.user }}{% endblock%}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/detail.css' %}?{% cache_bust %}" />

{% endblock %}

{% block content %}
<div class="detail-container">
    <div class="post-image">
        <img src="{{post.image.url}}" alt="{{ post.location }}">
    </div>

    <div class="post-text">
        <div>
            <h1>{{ post.title }}</h1>
            <small>{{ post.created|date:"d F Y" }}</small>
            {% if user.is_authenticated and request.user == post.user %}
            <a class="edit-btn" href="{% url 'social:edit_post' pk=post.pk %}"><i class="bi bi-pencil-fill"></i></a>
            {% endif %}
        </div>
        
        <div class="post-description">
            <div>
                <h2>{{ post.destination }}</h2>
                <h3>{{ post.location }}</h3>
            </div>
            <h4>-</h4>
            <div>
                <h4>{{ post.dest_type }}</h4>
            </div>
        </div>

        <hr>
    
        <div class="post-content">
            <p>{{ post.content }}</p>
        </div>

        <hr>
    
        
        <div class="analytics">
            <div>{{post.Comments.count}}&nbsp;<i class="bi bi-chat"></i></div>
            {% include 'social/likes.html' %}
        </div>
        
        
    </div>

</div>

{% include 'social/comment.html' %}




{% endblock%}

{% block js %}
<script src="https://unpkg.com/htmx.org@1.6.0"></script>
<script>
    document.body.addEventListener('htmx:configRequest', (e) => {
    e.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
    })
</script>
{% endblock %}
    
    

travel_social/social/templates/social/index.html
{% extends 'base.html' %}
{% load static %}
{% load cache_bust %}


{% block title %}All Posts{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/posts.css' %}?{% cache_bust %}">
{% endblock %}

{% block content %}
    {% if all_posts %}
        <ul class="posts-container">    
            {% for post in all_posts %}
            <li class="post-item">
                <a href="{% url 'social:detail' post.id %}">
                
                    <!--<span style="display:block;">{{ post.dest_type }}</span>
                    <span style="display:block;">{{ post.location }}</span>-->
                    <img src="{{ post.image.url }}" alt="{{ post.destination}}" width="" height="">
                    <div class="item-overlay">
                        <div>
                            <span>{{post.title}}</span>
                            <span style="display:block;"><small style="font-weight: 600;">{{ post.destination }}</small></span>
                        </div>

                        <div>
                            <span>{{post.Comments.count}}&nbsp;<i class="bi bi-chat"></i></span>
                            <span style="margin:0 10px;">{{post.likes.count}}&nbsp;<i class="bi bi-balloon-heart"></i></span>
                        </div>
                    </div>
                </a>
            </li>
            {% endfor %}
        </ul>
        {% else %}
                <p>No posts yet</p>
                <a href="{% url 'social:create_post' %}">create post</a>
        {% endif %}

    

{% endblock %}
    
    

travel_social/social/templates/social/likes.html
<div id="likesarea">
    <span>
        {{post.likes.count}} 
        {% if post.likes.count == 1 %}
            like
        {% else %}
            likes
        {% endif %}
    </span>

    <span>
        <button hx-post="{% url 'social:like_post' post.id %}" 
        id="like-button" hx-target="#likesarea" hx-swap="outerHTML">
        {% if request.user in post.likes.all %}
        <i class="bi bi-balloon-heart-fill"></i>
        {% else %}
        <i class="bi bi-balloon-heart"></i>
        {% endif %}
        </button>
    </span>
</div>

travel_social/social/templates/social/post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Post</title>
</head>
<body>
    <form method="POST" action="{% url 'social:create_post' %}" enctype=multipart/form-data>{% csrf_token %}
        {{form.as_p}}
        <button type="post">create post</button>
    </form>

    
    
</body>

</html>