travel_social/social/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'social'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('create-post/', views.create_post, name='create_post'),
    path('<int:pk>/edit/', views.edit_post, name='edit_post'),
    path('<int:pk>/like/', views.like_post, name='like_post'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

travel_social/travel_social/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('social/', include('social.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

travel_social/social/models.py
from django.conf import settings
from django.db import models

from django.contrib.auth import get_user_model
from django.utils import timezone
User=get_user_model()



# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(default=timezone.now)
    published = models.DateTimeField(blank=True, null=True)
    title = models.CharField(max_length=250)
    destination = models.CharField(max_length=50)
    dest_type = models.CharField(max_length=50)
    location = models.CharField(max_length=250)
    image = models.ImageField(upload_to='uploads/', height_field=None, width_field=None)
    content = models.TextField()
    likes = models.ManyToManyField(User, blank=True, related_name="collected_likes")

    def total_likes(self):
        return self.likes.count()

    def publish(self):
        self.published = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def created_recently(self):
        return self.created >= timezone.now() - datetime.timedelta(days=1)

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models .ForeignKey(Post, related_name="Comments", on_delete=models.CASCADE)
    text = models.TextField()
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return '%s - %s' % (self.post.title, self.post.user)

travel_social/social/forms.py
from django.forms import ModelForm
from django.db.models import fields
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    title = forms.TextInput()
    destination = forms.TextInput()
    dest_type = forms.TextInput()
    location = forms.TextInput()
    image = forms.ImageField()
    content = forms.Textarea()
    class Meta:
        model = Post
        fields = (
            'title',
            'destination',
            'dest_type',
            'location',
            'image',
            'content',
        )
        

class CommentForm(forms.ModelForm):
    text = forms.Textarea()
    class Meta:
        model = Comment
        fields = (
            'text',
        ) 
        widgets = {'text': forms.Textarea(attrs={'placeholder': 'comment', 'help_text': ''})}
        labels = {'text' : ''}

    

travel_social/social/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse
from django.template import loader
from django.contrib.auth.models import User
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.utils import timezone
from django.contrib.auth.decorators import login_required

# Create your views here.   
def index(request):
    template = 'social/index.html'
    all_posts = Post.objects.all

    context = {
        'all_posts': all_posts,
    }
    return render(request, template, context)

def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm()

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.user = request.user
            comment.created = timezone.now()
            comment.text = request.POST['text']
            comment.save()
            return redirect('social:detail', post.id)
    else:
        form: CommentForm()

    context = {
        'post': post,
        'form': form,
    }
    return render(request, 'social/detail.html', context)

@login_required
def create_post(request):
    template = 'social/post.html'
    form = PostForm(request.POST, request.FILES)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        print(request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.created = timezone.now()
            post.title = request.POST['title']
            post.dest_type = request.POST['dest_type']
            post.location = request.POST['location']
            post.image = request.FILES['image']
            post.content = request.POST['content']
            post.save()
            return redirect('social:detail', post.id)
    else:
        form: PostForm()

    context = {
        'form': PostForm,
    }
    return render(request, template, context)

def edit_post(request, pk):
    template = 'social/edit.html'
    post = get_object_or_404(Post, pk=pk)   
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(Commit=False)
            post.user = request.user
            post.created = timezone.now()
            post.save()
            return redirect('social:detail', pk=post.pk)
        else:
            form = PostForm(instance=post)
    
    context = {
        'form': PostForm
    }
    return render(request, template, context)

def like_post(request, pk):
    if request.method == 'POST':
        instance = Post.objects.get(pk=pk)
        if not instance.likes.filter(id=request.user.id).exists():
            instance.likes.add(request.user)
            instance.save()
            return render(request, 'social/likes.html', context={'post': instance})
        else:
            instance.likes.remove(request.user)
            instance.save()
            return render(request, 'social/likes.html', context={'post': instance})

travel_social/social/templates/base.html
{% load cache_bust %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%}{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/main.css' %}?{% cache_bust %}" />
    <link rel="stylesheet" href="{% static 'css/nav.css' %}?{% cache_bust %}" />
    <link rel="stylesheet" href="{% static 'css/footer.css' %}?{% cache_bust %}" />
    {% block styles %}{% endblock %}
    <!-- FONTS -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <!-- ICONS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

</head>
<body>
    {% include 'navbar.html' %}

    <div class="wrapper">
        <div class="container">
            {% block content %}{% endblock %}
        </div>
    </div>

    {% include 'footer.html' %}
</body>

<script src="{% static 'js/main.js' %}?{% cache_bust %}"></script>

<script>
{% block js %}{% endblock %}
</script>

</html>

travel_social/social/templates/footer.html
<footer>
    <p><small>Designed and Developed by <a href="htpps://www.prettypandey.dev" target="_blank">Pretty Pandey</a></small></p>
</footer>

travel_social/social/templates/navbar.html
<nav>
    <div>
        <a href="{% url 'landing' %}"><i class="bi bi-house-fill"></i></a>
    </div>

    <div>
        <a href="{% url 'social:index' %}">all posts</a>
        <a href="{% url 'social:create_post' %}">create post</a>
    </div>

    <div>
        {% if user.is_authenticated %}
        <a href="">@{{ user.username }}</a>
        <a href="{% url 'logout' %}">logout</a>
        {% else %}
            <a href="{% url 'signup' %}">signup</a>
            <a href="{% url 'login' %}">login</a>
        {% endif %}
    </div>
</nav>